In [2]:
import numpy as np

# Basics

In [ ]:
#linspace
x = np.linspace(10, 20, 5) # (start, stop, number of intervals) to obtain the elements add (stop-start)/(num-1)

#matrix multiplication
x = np.array([[1,2], [3,4], [5,6]])
y = np.array([[1,2,3], [4,5,6]])
np.dot(x, y) # matrix multiplication = first row is 1*(1,2,3)+2*(4,5,6), second row is 3*(1,2,3)+4*(4,5,6)
x@y

#reshape to column or row vectors 
x = np.arange(3)
x.reshape((1, x.size)) #row vector
x.reshape((x.size, 1)) #column vector

x.ravel() #reshape to one dimensional array
#Pay attention that 1-dimensional arrays (shape (n,)) are NOT row vectors (shape (1, n))

#reduce functions
#iterate over array as it was one dimensional
x= np.array([[1,2,3], [1,2,3]])

x.sum()
# can also iterate over one axis
#0=rows, each row collapse into the final result each
x.sum(0) # [2,4,6]
x.sum(1) # [6,6]


array([[ 0,  1,  2,  3],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

# Slicing

In [ ]:
# Multidimensional arrays allow can be sliced in each axis

x = np.arange(15).reshape(3,5)
#[
#[ 0, 1, 2, 3, 4],
#[ 5, 6, 7, 8, 9],
#[10, 11, 12, 13, 14]
#]
x[1, 0:3]
# [5, 6, 7]

# If we want a 1-row matrix, we have to specify also the end of the
x[1:2, 0:3]
# [[5, 6, 7]]
# columns matrix
x[0:3, 0:1]

# Numpy allows for advanced indexing: we can use numpy integer arrays and boolean

#integer index represents which elements to take
x = np.arange(12).reshape(3,4) 
#[[ 0  1  2  3]
#[ 4  5  6  7]
#[ 8  9 10 11]]
idx = np.array([0, 0, 2])
x[idx, :]
# [[ 0,  1,  2,  3],
# [ 0,  1,  2,  3],
# [ 8,  9, 10, 11]]

# boolean indexing is like a mask


# Broadcasting

+ 1’s will be prepended to the shapes of smaller arrays until
all arrays have the same number of dimensions
+ Axes with shape 1 are treated as if they had the same dimension as the array with largest size along the axis, and
all elements were the same along the axis

In [43]:

#### es 7a
def f(m,n):
    M = np.ones((m, n))
    x = np.arange(m).reshape((m,1))
    y = np.arange(n).reshape((1,n))
    print(M)
    print(x)
    print(y)
    M = M * x
    print(M)
    M = M * y
    return M
    
    #return np.fromfunction(lambda i, j: i * j, (m, n), dtype=np.float64)

    """
    
    """
#print(f(3,3))

#### es 7b

def f2(arr):
    return arr/arr.sum(0)

#print(f2(np.array([[1, 8], [1, 2]])))

def f3(arr):
    return arr/arr.sum(1).reshape((arr.shape[1], 1))

print(f3(np.array([[2, 8], [1, 2]])))

[[0.2        0.8       ]
 [0.33333333 0.66666667]]
